version: '3'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: medusa
      MYSQL_DATABASE: rws_booter
      # MYSQL_USER: myuser
      # MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
    volumes:
      - ./data:/var/lib/mysql
    # networks:
    #   - service-network


  phpmyadmin:
    image: phpmyadmin
    ports:
      - 9999:80
    links:
      - db:db
    # networks:
    #   - service-network
    depends_on:
      db:
        condition: service_healthy

