version: '3'
services:
  postgres:
    image: postgres:15.1
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres_user
      - POSTGRES_PASSWORD=postgres_pwd
  phppgadmin:
    image: qnapsystem/phppgadmin:7.13.0-1
    restart: on-failure
    ports:
      - 7070:80
    depends_on:
      - postgres
    environment:
      - PHP_PG_ADMIN_SERVER_HOST=postgres
      - PHP_PG_ADMIN_SERVER_PORT=5432

volumes:
    postgres_db:
