# ============================== Filebeat inputs ===============================

filebeat.inputs:
  # - type: filestream
  - type: log
    id: asimov.api-server
    enabled: true
    fields:
      app_name: asimov.api-server
    fields_under_root: true
    json.keys_under_root: true
    json.add_error_key: true
    paths:
      - /home/ubuntu/asimov/api-server/logs/current.log

# ============================== Elasticsearch output ===========================

output.elasticsearch:
  hosts: ["http://elastic.asimov.lab.gtcafe.com:9200"]
  # username: "elastic"
  # password: "your_elastic_password"

# ============================ Setup Kibana (optional) ==========================

setup.kibana:
  host: "http://kibana.asimov.lab.gtcafe.com:5601"

# ============================ Logging ==========================================

logging.level: info
